custom_build('example-html-image',
             'docker build -t $EXPECTED_REF src/hello-world',
             deps=['src/hello-world'])
k8s_yaml('kubernetes.yaml')
k8s_resource('example-html', port_forwards=8000)
